# Tipo de Base de Datos activa: sqlite, postgresql, mysql
db.type=sqlite

# Configuración por defecto: SQLite (Autocontenida en archivo local)
db.sqlite.url=jdbc:sqlite:zoom_sockets.db

# Configuración alternativa: PostgreSQL (Descomentar para usar)
# db.postgresql.url=jdbc:postgresql://localhost:5432/zoom_sockets
# db.postgresql.user=postgres
# db.postgresql.password=postgres

# Configuración alternativa: MySQL (Descomentar para usar)
# db.mysql.url=jdbc:mysql://localhost:3306/zoom_sockets
# db.mysql.user=root
# db.mysql.password=root
